[package]
name = "weasel-gen"
description = "Random ascii generation animation until target string is met"
version = "1.0.0"
edition = "2024"
include = ["src/main.rs", "LICENSE-*", "README.md"]

[[bin]]
name = "wgen"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
rand = "0.9.1"
